services:

  - type: web

    name: wallet-monitor

    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:

      - key: BSC_RPC_URL
        value: https://bsc-dataseed.binance.org

      - key: ETH_RPC_URL
        value: https://cloudflare-eth.com

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: TELEGRAM_CHAT_ID
        sync: false

      - key: POLL_SECONDS
        value: "60"

      - key: TELEGRAM_POLL_SECONDS
        value: "5"

      - key: ENABLE_MONITOR
        value: "1"

      - key: ENABLE_TELEGRAM
        value: "1"
